version: "3"
services:
  backend:
    container_name: t9-backend
    build:
      dockerfile: ./Dockerfile.local
      context: ./packages/backend
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/var/www
      - /var/www/node_modules
    networks:
      - t9-network
  frontend:
    container_name: t9-frontend
    build:
      dockerfile: ./Dockerfile.local
      context: ./packages/frontend
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/var/www
      - /var/www/node_modules
    networks:
      - t9-network

networks:
  t9-network:
    driver: bridge
