version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.local
      args:
        user: t9-admin
        uid: 1000
    image: t9-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - t9-app
    working_dir: /var/www/backend
    volumes:
      - ./packages/backend:/var/www/backend

  nginx:
    image: nginx:1.17-alpine
    container_name: t9-nginx
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - t9-app

networks:
  t9-app:
    driver: bridge
