version: "3"
services:
  backend:
    container_name: backend
    build:
      dockerfile: ./Dockerfile.local
      context: ./packages/backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:3001"
    working_dir: /var/www/backend
    volumes:
      - ./packages/backend:/var/www/backend
      - /var/www/backend
    networks:
      - t9-network
  frontend:
    container_name: frontend
    build:
      dockerfile: ./Dockerfile.local
      context: ./packages/frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:3000"
    working_dir: /var/www/frontend
    volumes:
      - ./packages/frontend:/var/www/frontend
      - /var/www/frontend
    networks:
      - t9-network

networks:
  t9-network:
    driver: bridge