version: "3.9"
services:
  t9-backend:
    image: node:17-buster
    container_name: t9-backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.local
    restart: unless-stopped
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - t9-app
    working_dir: /var/www/backend
    volumes:
      - ./:/var/www/backend

  t9-nginx:
    image: nginx:1.17-alpine
    container_name: t9-nginx
    restart: unless-stopped
    ports:
      - "3000:1337"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - t9-app

networks:
  t9-app:
    driver: bridge
